@HostAddress = https://localhost:7044

### 1. перевірка генерації хешу 
POST {{HostAddress}}/api/block/hash
Content-Type: application/json

"Тестовий документ"

### 2. додавання першого блоку в ланцюг
POST {{HostAddress}}/api/block/block
Content-Type: application/json
X-API-KEY: MySuperSecretKey123

"Це дані мого першого блоку"

### 3. додавання другого блоку
POST {{HostAddress}}/api/block/block
Content-Type: application/json
X-API-KEY: MySuperSecretKey123

"А це вже другий документ для ланцюга"

### 4. перевірка надійності валідація всього блокчейну
GET {{HostAddress}}/api/block/validate